
= Reference Documents

The following is a list of Reference Documents with a direct bearing on the content of this document.

[cols="2,7,1"]
|===
| Reference | Document Details | Version

| [[EOEPCA-UC]][EOEPCA-UC]
a|
--
EOEPCA - Use Case Analysis +
EOEPCA.TN.005 +
https://eoepca.github.io/use-case-analysis
--
a|
--
Issue TBD, +
dd/mm/yyy
--

| [[EP-FM]][EP-FM]
a|
--
Exploitation Platform - Functional Model, +
ESA-EOPSDP-TN-17-050
--
a|
--
Issue 1.0, +
30/11/2017
--

| [[TEP-OA]][TEP-OA]
a|
--
Thematic Exploitation Platform Open Architecture, +
EMSS-EOPS-TN-17-002
--
a|
--
Issue 1, +
12/12/2017
--

| [[WPS-T]][WPS-T]
a|
--
OGC Testbed-14: WPS-T Engineering Report, +
OGC 18-036r1, +
http://docs.opengeospatial.org/per/18-036r1.html
--
a|
--
18-036r1, +
07/02/2019
--

| [[CWL]][CWL]
a|
--
Common Workflow Language Specifications, +
https://www.commonwl.org/v1.0/
--
a|
--
v1.0.2
--

| [[TB13-AP]][TB13-AP]
a|
--
OGC Testbed-13, EP Application Package Engineering Report, +
OGC 17-023, +
http://docs.opengeospatial.org/per/17-023.html
--
a|
--
17-023, +
30/01/2018
--

| [[TB13-ADES]][TB13-ADES]
a|
--
OGC Testbed-13, Application Deployment and Execution Service Engineering Report, +
OGC 17-024, +
http://docs.opengeospatial.org/per/17-024.html
--
a|
--
17-024, +
11/01/2018
--

| [[TB14-AP]][TB14-AP]
a|
--
OGC Testbed-14, Application Package Engineering Report, +
OGC 18-049r1, +
http://docs.opengeospatial.org/per/18-049r1.html
--
a|
--
18-049r1, +
07/02/2019
--

| [[TB14-ADES]][TB14-ADES]
a|
--
OGC Testbed-14, ADES & EMS Results and Best Practices Engineering Report, +
OGC 18-050r1, http://docs.opengeospatial.org/per/18-050r1.html
--
a|
--
18-050r1, +
08/02/2019
--

| [[OS-GEO-TIME]][OS-GEO-TIME]
a|
--
OpenSearch GEO: OpenSearch Geo and Time Extensions, +
OGC 10-032r8, +
http://www.opengeospatial.org/standards/opensearchgeo
--
a|
--
10-032r8, +
14/04/2014
--

| [[OS-EO]][OS-EO]
a|
--
OpenSearch EO: OGC OpenSearch Extension for Earth Observation, +
OGC 13-026r9, +
http://docs.opengeospatial.org/is/13-026r8/13-026r8.html
--
a|
--
13-026r9, +
16/12/2016
--

| [[GEOJSON-LD]][GEOJSON-LD]
a|
--
OGC EO Dataset Metadata GeoJSON(-LD) Encoding Standard, +
OGC 17-003r1/17-084
--
a|
--
17-003r1/17-084
--

| [[GEOJSON-LD-RESP]][GEOJSON-LD-RESP]
a|
--
OGC OpenSearch-EO GeoJSON(-LD) Response Encoding Standard, +
OGC 17-047
--
a|
--
17-047
--

| [[CEOS-OS-BP]][CEOS-OS-BP]
a|
--
CEOS OpenSearch Best Practise, +
http://ceos.org/ourwork/workinggroups/wgiss/access/opensearch/
--
a|
--
v1.2, +
13/06/2017
--

| [[OIDC]][OIDC]
a|
--
OpenID Connect Core 1.0, +
https://openid.net/specs/openid-connect-core-1_0.html
--
a|
--
v1.0, +
08/11/2014
--

| [[OGC-CSW]][OGC-CSW]
a|
--
OGC Catalogue Services 3.0 Specification - HTTP Protocol Binding (Catalogue Services for the Web), +
OGC 12-176r7, +
http://docs.opengeospatial.org/is/12-176r7/12-176r7.html
--
a|
--
v3.0, +
10/06/2016
--

| [[OGC-WMS]][OGC-WMS]
a|
--
OGC Web Map Server Implementation Specification, +
OGC 06-042, +
http://portal.opengeospatial.org/files/?artifact_id=14416
--
a|
--
v1.3.0, +
05/03/2006
--

| [[OGC-WMTS]][OGC-WMTS]
a|
--
OGC Web Map Tile Service Implementation Standard, +
OGC 07-057r7, +
http://portal.opengeospatial.org/files/?artifact_id=35326
--
a|
--
v1.0.0, +
06/04/2010
--

| [[OGC-WFS]][OGC-WFS]
a|
--
OGC® Web Feature Service 2.0 Interface Standard – With Corrigendum, +
OGC 09-025r2, +
http://docs.opengeospatial.org/is/09-025r2/09-025r2.html
--
a|
--
v2.0.2, +
10/07/2014
--

|===
