
= Reference Documents

The following is a list of Reference Documents with a direct bearing on the content of this document.

[cols="1,5,1"]
|===
| Reference | Document Details | Version

| [[EOEPCA-UC]][EOEPCA-UC]
a|
--
EOEPCA - Use Case Analysis (https://eoepca.github.io/use-case-analysis[https://eoepca.github.io/use-case-analysis]), +
EOEPCA.TN.005
--
a|
--
Issue TBD, +
dd/mm/yyy
--

| [[EP-FM]][EP-FM]
a|
--
Exploitation Platform - Functional Model, +
ESA-EOPSDP-TN-17-050
--
a|
--
Issue 1.0, +
30/11/2017
--

| [[TEP-OA]][TEP-OA]
a|
--
Thematic Exploitation Platform Open Architecture, +
EMSS-EOPS-TN-17-002
--
a|
--
Issue 1, +
12/12/2017
--

| [[WPS-T]][WPS-T]
a|
--
OGC Testbed-14: WPS-T Engineering Report, +
OGC 18-036r1, http://docs.opengeospatial.org/per/18-036r1.html
--
a|
--
18-036r1, +
07/02/2019
--

| [[CWL]][CWL]
a|
--
Common Workflow Language Specifications, +
https://www.commonwl.org/v1.0/
--
a|
--
v1.0.2
--

| [[TB13-AP]][TB13-AP]
a|
--
OGC Testbed-13, EP Application Package Engineering Report, +
OGC 17-023, http://docs.opengeospatial.org/per/17-023.html
--
a|
--
17-023, +
30/01/2018
--

| [[TB13-ADES]][TB13-ADES]
a|
--
OGC Testbed-13, Application Deployment and Execution Service Engineering Report, +
OGC 17-024, http://docs.opengeospatial.org/per/17-024.html
--
a|
--
17-024, +
11/01/2018
--

| [[TB14-AP]][TB14-AP]
a|
--
OGC Testbed-14, Application Package Engineering Report, +
OGC 18-049r1, http://docs.opengeospatial.org/per/18-049r1.html
--
a|
--
18-049r1, +
07/02/2019
--

| [[TB14-ADES]][TB14-ADES]
a|
--
OGC Testbed-14, ADES & EMS Results and Best Practices Engineering Report, +
OGC 18-050r1, http://docs.opengeospatial.org/per/18-050r1.html
--
a|
--
18-050r1, +
08/02/2019
--

| [[OGC_10-032r8]][OGC_10-032r8]
a|
--
OpenSearch GEO: OpenSearch Geo and Time Extensions, +
OGC 10-032r8, http://www.opengeospatial.org/standards/opensearchgeo
--
a|
--
OGC 10-032r8, +
14/04/2014
--

| [[OGC_13-026r9]][OGC_13-026r9]
a|
--
OpenSearch EO: OGC OpenSearch Extension for Earth Observation, +
OGC 13-026r9, http://docs.opengeospatial.org/is/13-026r8/13-026r8.html
--
a|
--
OGC 13-026r9, +
16/12/2016
--

| [[OGC_17-003r1_17-084]][OGC_17-003r1_17-084]
a|
--
OGC EO Dataset Metadata GeoJSON(-LD) Encoding Standard, +
OGC 17-003r1/17-084
--
a|
--
OGC 003r1/17-084
--

| [[OGC_17-047]][OGC_17-047]
a|
--
OGC OpenSearch-EO GeoJSON(-LD) Response Encoding Standard, +
OGC 17-047
--
a|
--
OGC 17-047
--

| [[CEOS-OS-BP]][CEOS-OS-BP]
a|
--
CEOS OpenSearch Best Practise, +
http://ceos.org/document_management/Working_Groups/WGISS/Interest_Groups/OpenSearch/CEOS-OPENSEARCH-BP-V1.2.pdf
--
a|
--
v1.2, +
13/06/2017
--

|===
